spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

file.upload-directory=${FILE_UPLOAD_DIR}
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

vps.host=${VPS_HOST}
vps.port=${VPS_PORT}
vps.username=${VPS_USERNAME}
vps.password=${VPS_PASSWORD}
vps.base-path=${VPS_BASE_PATH}
vps.base-url=${VPS_BASE_URL}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}
jwt.verification.expiration=${JWT_VERIFICATION_EXPIRATION}

app.name=${APP_NAME}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID}

app.frontend.url=${FRONTEND_URL}
app.base-url=${APP_BASE_URL}
app.api-url=${APP_API_URL}

logging.level.org.springframework.security=${LOG_LEVEL_SECURITY}
logging.level.com.masasilam.app=${LOG_LEVEL_APP}
logging.level.org.springframework.web=${LOG_LEVEL_WEB}
logging.level.org.mybatis=${LOG_LEVEL_MYBATIS}
logging.level.org.apache.ibatis=${LOG_LEVEL_IBATIS}