package com.naskah.demo.model.enums;

public enum NotificationType {
    PROJECT_REACTION,
    PROJECT_COMMENT,
    PAGE_REACTION,
    PAGE_COMMENT,
    COMMENT_REPLY,
    MEMBER_JOINED,
    WORK_COMPLETED,
    PROJECT_COMPLETED,
    PROJECT_FOLLOW,
    QUALITY_ASSESSMENT,
    PROJECT_READY_FOR_COMPLETION,
    ISSUE_REPORTED,
    ISSUE_RESOLVED,
    COLLABORATION_INVITE,
    PROJECT_MILESTONE
}
